apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::014667131196:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-THKF5AO2Y95Q
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::014667131196:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-28T00:40:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "25005"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 9d6edafa-ea9e-4c20-9537-dc70df894fb8
