apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::014667131196:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-P569REWANSBB
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::<YOUR_ACCOUNT_ID>:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-28T18:13:53Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-01-28T18:13:53Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1472"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: b4128bc8-c977-4718-975e-56b0594533f2
