apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::014667131196:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-UAOS56CNIZKJ
      username: system:node:{{EC2PrivateDNSName}}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::014667131196:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-03T15:51:35Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-02-03T15:51:35Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1519"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 8d333e8e-1b8f-4c7f-927b-c31c46ffa136
