apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::014667131196:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1A4C9A4YSLZRK
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::014667131196:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-02T19:15:24Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-02-02T19:15:24Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1368"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: fdc3f182-2fcf-4a60-bfb5-dc2a7e14c146
